spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/coinportal
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://cortal-db-1.c7mfu0whlsaf.ap-northeast-2.rds.amazonaws.com:3306/temp?autoReconnetc=true
#    username: admin
#    password: zhxjf123
  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug

# jwt 관련 hash 생성 키
jwt:
  hash:
    key: coinportalUserAthenticationSecretKeyString&coinportalUserAthenticationSecretKeyString

# multipartFile 경로
file:
  #Window
  dir: C:\Users\choi\Desktop\coin-portal\Backend\Coin-portal\image
  # Linux
#  dir: /home/ubuntu/server/image


# 카카오 OAuth 연결 정보
kakao:
  oauth:
    client_id: bbac0c1542268d22cd795e3d398071f5
    redirect_uri: http://localhost:8080/login&response_type=code